import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import ReduxProvider from "@/redux/ReduxProvider";
import AuthProvider from "@/components/providers/AuthProvider";
import { ToastContainer } from "react-toastify";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Pushfi",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider>
					<ReduxProvider>
						<AuthProvider>{children}</AuthProvider>
						<ToastContainer />
					</ReduxProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
